### ISSUE TITLE
${filename} always seems to point to the same file

### ISSUE THREAD

**Issue by TypicalHog** [RainCat1998/obsidian-custom-attachment-location#1]
Currently, I have all of my attached files in "assets".

I would like to have them in "assets/${filename}", but no matter which file I have open and dragging and dropping files into - all of the files go to "assets/Monitor" (Monitor.md was the first note I tried the plugin in).

I tried to restart Obsidian, reinstall the plugin etc.

**Comment by RainCat1998** [comment]
I need more information about this bug.
Can you upload your vault folder (with ".obsidian" folder) and some screenshots so I can figure out the problem?

**Comment by RainCat1998** [comment]
I just create a new notebook and have some tests. Everything works fine.
![image](https://user-images.githubusercontent.com/36730607/140450930-07c27b9c-a5e0-448f-8dc0-5ceee888e095.png)

**Comment by TypicalHog** [comment]
Here you go: [Test.zip](https://github.com/RainCat1998/obsidian-custom-attachment-location/files/7486467/Test.zip)

The above vault seems to have the same problem when I try to drag & drop a file. I'm on Windows 10, btw.

Expected:

![image](https://user-images.githubusercontent.com/11476902/140521878-7d134164-0863-4931-9f7e-cdce284803cb.png)

<br>

What I get:

![image](https://user-images.githubusercontent.com/11476902/140521916-5fe494d1-3b35-4ceb-b72a-fe042b653717.png)

**Comment by TypicalHog** [comment]
The files used to go to the same folder every time "assets/Monitor", but now, they all go straight to the Vault folder for some reason.

**Comment by TypicalHog** [comment]
I just realized - everything works fine when I paste from clipboard, but not when I drag and drop a file from file explorer.

**Comment by RainCat1998** [comment]
> Here you go: [Test.zip](https://github.com/RainCat1998/obsidian-custom-attachment-location/files/7486467/Test.zip)
> 
> The above vault seems to have the same problem when I try to drag & drop a file. I'm on Windows 10, btw.
> 
> Expected:
> 
> ![image](https://user-images.githubusercontent.com/11476902/140521878-7d134164-0863-4931-9f7e-cdce284803cb.png)
> 
> 
> What I get:
> 
> ![image](https://user-images.githubusercontent.com/11476902/140521916-5fe494d1-3b35-4ceb-b72a-fe042b653717.png)

The plugin doesn't support drag & drop event yet. Here's how it works.
I registered a custom paste event handler and change the location setting before obsidian save the file.
I will add support for "drag and drop" event in the next release.

**Comment by TypicalHog** [comment]
Oh, I see. My bad.

Thanks for the clarification.

**Comment by RainCat1998** [comment]
> Oh, I see. My bad.
> 
> Thanks for the clarification.

I have uploaded a new release to support "drag and drop" event. You can update the plugin and have a try.

**Comment by TypicalHog** [comment]
> > Oh, I see. My bad.
> > Thanks for the clarification.
> 
> I have uploaded a new release to support "drag and drop" event. You can update the plugin and have a test.

Works perfect, thank you!
