### ISSUE TITLE
[Feature request]  variable field for note creation date time 

### ISSUE THREAD

**Issue by andrewcrook** [RainCat1998/obsidian-custom-attachment-location#101]
Hi

Would it be possible to add a variable for the note creation date time.
Maybe get the data from the front-matter, so have an option field in the plugins settings to enter a field name.
It would be useful to be able to format the variables date time as well.

![Screenshot 2024-09-26 at 16 54 21](https://github.com/user-attachments/assets/5ed85098-ff41-445f-a14c-1e5ce2137c65)

**Comment by mnaoumov** [comment]
In https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/5.0.0 added tokens 

- `${fileCreationDate:format}`
- `${fileModificationDate:format}`
- `${frontmatter:key}`

And even custom tokens supported if none of the bult-ins work for you
