### ISSUE TITLE
[BUG] Letercase problem

### ISSUE THREAD

**Issue by MahiroCh** [RainCat1998/obsidian-custom-attachment-location#102]
No matter what settings are on, when renaming .md file with attachments in it by changing only one letter from uppercase to lowercase or vice versa, it treats the file as it was copy of existing file (which actually doesn't exist) and adds number or \_\_temp__ prefix to .md file.

If attachment bruhed, just create completely new vault, install extension with showed settings (in the video), create note, add any attachment you like and try to change case of the first letter of this note.

[BugError.zip](https://github.com/user-attachments/files/17175965/BugError.zip)

https://github.com/user-attachments/assets/16f88176-9787-4f5d-94b5-aa375fb0872d

UPD: Also another bug stems from this: auto renaming corresponding attachment folder stops working until you rename either file or folder to make both names identical.

**Comment by mnaoumov** [comment]
@MahiroCh attach your vault as a zip file

**Comment by MahiroCh** [comment]
Done

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.24.0
