### ISSUE TITLE
Question about storing attachments in relative to a project

### ISSUE THREAD

**Issue by 6StringSam** [RainCat1998/obsidian-custom-attachment-location#104]
Looking for a way to store attachments relative to the project. So based on the note path the asset location would just below the project folder.

Document path: Projects/X/Subject1/Issue1.md
Asset location: Projects/X/Assets

Here is my folder structure.

- Projects
	- X
		- Subject1
		- Subject2
		- Subject3
		- Assets
	- Y
		- Subject1
		- Subject2
		- Assets
	- Z
		- Subject1
		- Subject2
		- Assets

Thoughts?

**Comment by mnaoumov** [comment]
Currently this scenario is not possible. I will consider allowing setting like `${folderPath}/../Assets`

**Comment by mnaoumov** [comment]
In https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/5.0.0 you can just use `../Assets` setting
