### ISSUE TITLE
[BUG] Features do not work when you insert a picture into a note that opened in a new window

### ISSUE THREAD

**Issue by hmnijp** [RainCat1998/obsidian-custom-attachment-location#105]
Features do not work when you insert a picture into a note that opened in a _new window_.
At the same time, the functions work in the main window.

- Tested in **default sandbox**
[Obsidian Sandbox.zip](https://github.com/user-attachments/files/17264406/Obsidian.Sandbox.zip)

https://github.com/user-attachments/assets/82107a8e-25ae-4a53-a4f8-251131885e7a

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.24.0
