### ISSUE TITLE
[BUG] Can't move or rename file due to link in frontmatter

### ISSUE THREAD

**Issue by Inirdin** [RainCat1998/obsidian-custom-attachment-location#107]
I have file "platform.md" that is linked in frontmatter of file "game.md". The "platform.md" can't be moved or renamed. It works if the link is outside of the frontmatter in "game.md". 

[Example vault.zip](https://github.com/user-attachments/files/17270091/example.vault.zip)

https://github.com/user-attachments/assets/c08f638c-021b-47f2-8208-6f8e85bebfe3

**Comment by mnaoumov** [comment]
@Inirdin You didn't follow the GitHub issue template requirement

**Comment by Inirdin** [comment]
@mnaoumov added video

**Comment by Inirdin** [comment]
@mnaoumov this is still closed

**Comment by DaTebe** [comment]
I'm also facing the same issue. Currently moving files in my file explorer as workaround.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.25.0
