### ISSUE TITLE
[BUG] Canvas file handling exceptions

### ISSUE THREAD

**Issue by sudonem** [RainCat1998/obsidian-custom-attachment-location#108]
When creating Obsidian canvases, and setting an initial file name, or renaming existing canvas files, the custom attachment location plugin tosses a variety of exception errors. 

Functionality doesn't seem to be inhibited - just an oddity that might be causing issues elsewhere that I haven't yet noticed as I've only begun working with canvas files in my workflow.

Attaching a video, screenshots as well as console output exports.

- The Location for New File Attachments is: **99 - Files/media/${filename}**
- The Pasted File Name value is configured as: **${filename}-image-${date:YYYYMMDDHHmmss}**

![image](https://github.com/user-attachments/assets/362f2adf-bd58-4eb7-8f2d-6906a4f686bd)
***
![image](https://github.com/user-attachments/assets/d6942677-91a0-4fa2-a479-5f1633ff401d)

***
Sample Console Error 1:
![2024-10-06 13 11 49](https://github.com/user-attachments/assets/3c24c890-ffcc-4cde-9eef-745486472070)

Sample Console Error 2:
![image](https://github.com/user-attachments/assets/3b35b8dc-62ff-42e4-9593-d4ce5829d578)
***
https://github.com/user-attachments/assets/221fb798-fafb-468e-b715-b41e2da774df

[Obsidian Errors.zip](https://github.com/user-attachments/files/17270434/Obsidian.Errors.zip)

**Comment by mnaoumov** [comment]
@sudonem

Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.26.0

However the underlying issue is that your `canvas` files are not a valid `json`. On your video it's seen that `omnisearch` plugin also complains about invalid `json`.
