### ISSUE TITLE
[BUG] Flickering issues when moving files and folders

### ISSUE THREAD

**Issue by yohmni** [RainCat1998/obsidian-custom-attachment-location#109]
Recently, I've noticed significant flickering in Obsidian Files explorer when moving folders and files. Disabling the Custom Attachment plugin stopped the flickering. This issue occurs even when the folder contents don't include any images.

I'm not sure if this is caused by the Custom Attachment alone or if it's a result of interference from other plugins.

**Comment by mnaoumov** [comment]
You didn't follow the issue template
