### ISSUE TITLE
Feature Request: Option to add folder name to the renamed file

### ISSUE THREAD

**Issue by astrodad** [RainCat1998/obsidian-custom-attachment-location#11]
If I am saving attachments to a folder called "2022-01-26 Meeting", I would like the ability to rename an attachment to be {folderName}-{filename}.

That way I will recognize the file names even if they get decoupled from the folder, or if I am using an external tool to search by file names.

If you like the feature, I may give it a go in a local branch.

**Comment by RainCat1998** [comment]
You can just modify a few lines of code to add this feather.
