### ISSUE TITLE
[BUG] When I rename a .md file, it gives an error avoiding to rename the document

### ISSUE THREAD

**Issue by Kayfum** [RainCat1998/obsidian-custom-attachment-location#110]
A clear and concise description of the bug.

- I can't attach a video, bud this is the error message displayed ↴ 
![Captura de pantalla 2024-10-13 a las 14 02 46](https://github.com/user-attachments/assets/0b2f771a-6efd-4c9e-8a5e-a2b16e6953a8)

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.24.0
