### ISSUE TITLE
[BUG] Cannot paste text in Canvas

### ISSUE THREAD

**Issue by scambier** [RainCat1998/obsidian-custom-attachment-location#111]
- Enable Custom Attachment Location as the only plugin on a vault
- Create a canvas
- Make 2 nodes, and a link between them
- Double click on the link to edit its label, **you can't paste text** (right click > paste doesn't work either)
- Group the nodes and edit the group's label, **you can't paste text**

Pasting text still works inside the nodes, just not on the links or groups titles

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.27.0
