### ISSUE TITLE
[BUG] Flickering issue when renaming/moving files and folders

### ISSUE THREAD

**Issue by Nydid** [RainCat1998/obsidian-custom-attachment-location#112]
Like #109 and #110. When using this plugin, renaming files and/or moving them causes flickering as the files get renamed back and forth between the old name and the new name. Same issue with moving the file, it flickers between its old position and new position. This causes issues with syncing plugins as it creates a lot of syncing events.

- Please attach a video of the issue.
![Obsidian_PLK0U4ad5i](https://github.com/user-attachments/assets/75e8af1c-008d-4356-99cd-eaa3e2baa341)

- Please attach a sample vault where the issue can be reproduced.
[Flicker Rename Test.zip](https://github.com/user-attachments/files/17365973/Flicker.Rename.Test.zip)

**Comment by frigvid** [comment]
This problem doesn't occur just when renaming or moving files, but also folders. In fact, if `Keep empty attachment folders` aren't enabled, it removes the parent directory of the child directory entirely if you move the child outside the parent, and the parent is empty. Which shouldn't happen, considering that the parent folder isn't the attachment folder, it's the parent.

**Comment by technotherion** [comment]
It seems that the more plugins you have that handle changing something upon movement of a file, the more it flickers. 

This may also vary between sync services. I'm using Dropbox.

For example, with Folder Notes, there is an option that changes the name of the folder name to the name of the folder note. Doing this causes a conflict between both Custom Attachment Location where the file will bounce back and forth between the new directory (with the new folder note name) and the old directory for a while. 

I've simply disabled "automatically rename attachment folders" to solve the flickering.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.24.0
