### ISSUE TITLE
[BUG] Delete orphan attachments

### ISSUE THREAD

**Issue by dbloper** [RainCat1998/obsidian-custom-attachment-location#115]
When I delete a note, the attached files are not deleted

https://github.com/user-attachments/assets/5f9b2848-d1b8-4e22-b4bc-03ea46751e56

**Comment by mnaoumov** [comment]
A clear and concise description of the bug.

- Please attach a video of the issue.
- **Please attach a sample vault where the issue can be reproduced.**

BUGS WITHOUT PROVIDED INFORMATION WILL BE CLOSED WITHOUT INVESTIGATION
