### ISSUE TITLE
[FR] Location for new attachments organized by file types on specific sub-folders

### ISSUE THREAD

**Issue by DesignBeGo** [RainCat1998/obsidian-custom-attachment-location#118]
### Description

Attachments organization based on file types inside sub-folders on the desired attachments location.

### Details

x = image file
z = document pdf file
q = video file
y = audio file

By creating sub folders on the selected attachment folder in obsidian settings:

As an example folder structure with an specified folder and subfolders:
![image](https://github.com/user-attachments/assets/ac9144c4-7e12-4c17-b067-3fd51803daab)

- Extras 
	**- Attachments** 
		- Images ("For filetypes": avif, bmp, gif, jpeg, jpg, png, svg, webp)  
		- Videos ("": mkv, mov, mp4, ogv, webm)  
		- Audios ("": flac, m4a, mp3, ogg, wav, webm, 3gp)  
		- PDF's ("": PDF)
		
In settings i may select a subfolder and a file extension (or a list of file extensions separated by commas like above):

- .png = Extras/attachments/Images
- .jpg = Extras/attachments/Images
- .mp3 = Extras/attachments/Audio
- .mp4 = Extras/attachments/video
- .pdf = Extras/attachments/PDF's
![Obsidian_vT9IIKg16A](https://github.com/user-attachments/assets/ead6ff68-a665-4db6-9651-ed6e39934ab5)

So:
File x is dropped on note a.
->File goes directly to the path "Extras/attachments/Images" and is renamed according to the established settings.
File z is dropped on note a.
->File goes directly to the path "Extras/attachments/PDF's" as is.

### Desired Behavior

When I drop a file it goes direclty to a specified folder according to the file type/extension it has.

 

### Current Behavior

A folder is created in relation to the name and path of the current note where the file is dropped. It works, but it would be useful to have more options.

### Attachments

- Please attach a video showing the current behavior (I don't beleive a video is necessary)
- Please attach a sample vault where the desired Feature Request could be applied:
->  here it is
[example vault with attachments inside Extras folder.zip](https://github.com/user-attachments/files/17545384/example.vault.with.attachments.inside.Extras.folder.zip)

### Confirmations

- [X] I attached a video showing the current behavior
- [X] I attached a sample vault where the desired Feature Request could be applied
- [X] I have tested the issue with the latest version
- [X] I have checked for existing Feature Requests

**Comment by mnaoumov** [comment]
This seems like a too specific use case.

In https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/5.0.0 I added the ability to provide custom tokens, so you can implement the logic you need in a simple function
