### ISSUE TITLE
[BUG] Delete orphan attachments doesn't work

### ISSUE THREAD

**Issue by nameless66** [RainCat1998/obsidian-custom-attachment-location#119]
### Description

Hey there,

the option "Delete orphan attachments" doesn't work. The inserted files (Screenshot copy/pasted ) won't be deleted after deletion of the md-file.

Only setting I changed is:
Location for new attachments to
./_resources/${filename}.resources/${originalCopiedFilename}

But also tried different other paths, like ./attachments or ./assets/${filename} (Default setting)

Remaining settings have not been changed.

Thx in advance

### Steps to Reproduce

-

### Expected Behavior

-

### Actual Behavior

-

### Environment Information

- **Plugin Version**: 4.27.2
- **Obsidian Version**: 1.7.4
- **Operating System**: Mac OSX 14.6.1 (Sonoma)

### Attachments

-

### Confirmations

- [X] I attached a video showing the issue
- [X] I attached a sample vault where the issue can be reproduced
- [X] I have tested the issue with the latest version
- [X] I have checked for existing issues

**Comment by mnaoumov** [comment]
@nameless66 you didn't attach mandatory information
