### ISSUE TITLE
Drag-n-Drop file from explorer doesn't copy file to obsidian vault

### ISSUE THREAD

**Issue by SpL1Ne** [RainCat1998/obsidian-custom-attachment-location#12]
plugin settings:
location for new attachments: `./${filename}`

plugin version: 0.0.6
obsidian version: 0.13.23

When I drag-n-drop image or other file and folder for this note wasn't created before, plugin just create attachment folder without copying file to this attachment folder.
Can recreate in new vault with legacy editor, but can't understand why sometimes It works and sometimes not. Mostly not is attachment folder wasn't created by plugin before. Can post video if you need.

**Comment by EricWiener** [comment]
I believe this is caused by using `mkdir` and also updating the default attachment file for the vault. Updating the vault isn't synchronous (I believe) so checking if the directory exists doesn't actually guarantee it won't be created. I solved this problem by removing all `mkdir` since Obsidian will create the attachments directory for you automatically if it doesn't exist.

**Comment by RainCat1998** [comment]
> plugin settings: location for new attachments: `./${filename}`
> 
> plugin version: 0.0.6 obsidian version: 0.13.23
> 
> When I drag-n-drop image or other file and folder for this note wasn't created before, plugin just create attachment folder without copying file to this attachment folder. Can recreate in new vault with legacy editor, but can't understand why sometimes It works and sometimes not. Mostly not is attachment folder wasn't created by plugin before. Can post video if you need.



> I believe this is caused by using `mkdir` and also updating the default attachment file for the vault. Updating the vault isn't synchronous (I believe) so checking if the directory exists doesn't actually guarantee it won't be created. I solved this problem by removing all `mkdir` since Obsidian will create the attachments directory for you automatically if it doesn't exist. This only occurs when the first attachment is added and the attachment folder doesn't exist yet.

Can you post your vault folder ?

**Comment by RainCat1998** [comment]
> I believe this is caused by using `mkdir` and also updating the default attachment file for the vault. Updating the vault isn't synchronous (I believe) so checking if the directory exists doesn't actually guarantee it won't be created. I solved this problem by removing all `mkdir` since Obsidian will create the attachments directory for you automatically if it doesn't exist. This only occurs when the first attachment is added and the attachment folder doesn't exist yet.

I did some tests and It is really wired how obsidian handle attachments folder.
If using absolute path for attachment folder, obsidian will not automatically create attachments directory.
If using relative path, obsidian will create the attachments directory automatically. If I create attachment folder in my plugin, obsidian will not able to create the folder again and copy process get interrupted. This problem only occurs when drag-drop files which cannot recognized by obsidian(like ".xmind", or ".ahk". Copying "pdf", "txt" doesn't trigger this).

**Comment by RainCat1998** [comment]
> I believe this is caused by using `mkdir` and also updating the default attachment file for the vault. Updating the vault isn't synchronous (I believe) so checking if the directory exists doesn't actually guarantee it won't be created. I solved this problem by removing all `mkdir` since Obsidian will create the attachments directory for you automatically if it doesn't exist. This only occurs when the first attachment is added and the attachment folder doesn't exist yet.

I read obsidian code from "app.js" and found that obsidian call "saveattachment" function first before triggering "handleDrop" handler in my plugin. That's why this wired problem occurs.

**Comment by SpL1Ne** [comment]
> Can you post your vault folder ?

Empty vault. With default settings and only custom-attachment-location plugin installed. Tested with live preview mode with source code editing mode.
Created vault. Plugin works fine as should with any type of attachment. Close obsidian, open vault again and got this bug. Any drag-n-drop any attachment will create attachment folder without copying attachment.

**Comment by RainCat1998** [comment]
> > Can you post your vault folder ?
> 
> Empty vault with created one test note. With default settings and only custom-attachment-location plugin installed. Tested with live preview mode with source code editing mode. Created vault. Plugin works fine as should with any type of attachment. Close obsidian, open vault again and got this bug. Any drag-n-drop any attachment will create attachment folder without copying attachment.

I will update a new version as a work-around.
