### ISSUE TITLE
[Bug] Failed to load on Android

### ISSUE THREAD

**Issue by PiraSiraly** [RainCat1998/obsidian-custom-attachment-location#121]
### Description

Recently, the plugin can no longer be loaded in the Android version of Obsidian.

### Steps to Reproduce

1. Try to activate on Android
2. Failed to load

### Expected Behavior

Successful loading

### Actual Behavior

Loading failed

### Environment Information

- **Plugin Version**: [e.g., 4.28.1]
- **Obsidian Version**: [e.g., v1.7.7]
- **Operating System**: [e.g., Android 15]

### Attachments

[Test.zip](https://github.com/user-attachments/files/17838089/Test.zip)

https://github.com/user-attachments/assets/2d4e7634-3859-440c-b65f-ea43f9928546

### Confirmations

- [X] I attached a video showing the issue
- [X] I attached a sample vault where the issue can be reproduced
- [X] I have tested the issue with the latest version
- [X] I have checked for existing issues

**Comment by newsgood** [comment]
![Uploading Screenshot_20241122_093755_Obsidian.png…]()

**Comment by newsgood** [comment]
![Screenshot_20241122_093755_Obsidian](https://github.com/user-attachments/assets/c69386e0-3383-48f0-8900-1aabf28a2ffc)

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.28.5
