### ISSUE TITLE
[FR] Naming with randomly generated numbers

### ISSUE THREAD

**Issue by user30535** [RainCat1998/obsidian-custom-attachment-location#122]
### Description

Thanks for the plugin!

Is it possible to name the pasted files with randomly generated 6-digit numbers? The reason for this is that:

- I don’t want to reveal when the files were pasted, so I don’t want to use ${date}.
- I don’t want to reveal the sequence in which the files were pasted (e.g., "file 1," "file 2," etc.).

I think the best way to avoid duplicate file names without adding ${date} is to use randomly generated numbers.

Thank you!

### Details

-

### Desired Behavior

-

### Current Behavior

-

### Attachments

-

### Confirmations

- [X] I attached a video showing the current behavior
- [X] I attached a sample vault where the desired Feature Request could be applied
- [X] I have tested the issue with the latest version
- [X] I have checked for existing Feature Requests

**Comment by mnaoumov** [comment]
Added in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/5.0.0
