### ISSUE TITLE
[BUG] The action “Collect attachments...” does bypass the “renameOnlyImages” setting.

### ISSUE THREAD

**Issue by Nicostratus** [RainCat1998/obsidian-custom-attachment-location#123]
### Description

First of all, I would like to thank you for creating this plugin.
It is simply awesome. 

Recently while organizing my vault I noticed the following thing, I am not sure if it is intended:
Despite setting the following configuration:
“renameOnlyImages": true,
“renameCollectedFiles": true,

When you run the “Collect attachments for current note” action, the plugin renames all attachments, while theoretically it should rename only images.
Other attachments for example “zip”, “pdf” etc should have the file name unchanged

### Steps to Reproduce

1. Set following settings : “renameOnlyImages": true, “renameCollectedFiles": true,
2. Run “Collect attachments for current note” action on note that contains ZIP or PDF attachments 
3. Notice that all files will be renamed

### Expected Behavior

Other attachments for example “zip”, “pdf” etc should have the file name unchanged

### Actual Behavior

The plugin renames all attachments, while theoretically it should rename only images.

### Environment Information

- **Plugin Version**: v4.29.1
- **Obsidian Version**: v1.7.7
- **Operating System**: Windows 11

### Attachments

- Please attach a video showing the issue
- Please attach a sample vault where the issue can be reproduced

### Confirmations

- [X] I attached a video showing the issue
- [X] I attached a sample vault where the issue can be reproduced
- [X] I have tested the issue with the latest version
- [X] I have checked for existing issues

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.31.1
