### ISSUE TITLE
[BUG] Plugin sometimes breaks holding Ctrl to drag and drop attachment without copying and linking to external file

### ISSUE THREAD

**Issue by hsandt** [RainCat1998/obsidian-custom-attachment-location#125]
### Description

So far I've been using hold Ctrl + drag-and-drop attachment (picture, etc.) to a note to link to the external attachment instead of creating a local copy of the file, and it was compatible with Custom Attachment Location plugin.

But recently when I did it, it would ignore me holding Ctrl and still create a copy of the attachment, inserting a snippet `[[MyFile]]` instead of `[MyFile](file:///path/to/MyFile)`.

It doesn't happen 100% of the time but pretty often still, and once it creates a copy of the file you need to delete it, not just Undo the change so it's quite annoying.

### Steps to Reproduce

1. Open Sandbox vault
2. Install Custom Attachment Location plugin
3. Drag a file (.md, .png, etc.) into some note, holding Ctrl before release
...

### Expected Behavior

It should not copy the file and add en external `file:///` URI:

> `[MyFile](file:///path/to/MyFile)`

### Actual Behavior

The file has been added to plugin target location (default is `./assets/${filename}`) and a snippet `[[MyFile]]` points to the local copy of the file.

### Environment Information

- **Plugin Version**: 4.30.3
- **Obsidian Version**: v1.7.7
- **Operating System**: Ubuntu 22.04 LTS

### Attachments

- Video

As you can see it doesn't occur 100%: the first time it worked fine, the second time it didn't, although I held Ctrl in both cases

[2024-12-17 Obsidian Custom Attachment Location plugin inconsistently honors hold Ctrl drag external link.webm](https://github.com/user-attachments/assets/c8347a2a-4753-411f-8537-799677e36703)

- Sample vault

Not needed, Sandbox vault + plugin installed is fine

### Confirmations

- [X] I attached a video showing the issue
- [X] I attached a sample vault where the issue can be reproduced
- [X] I have tested the issue with the latest version
- [X] I have checked for existing issues

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.31.0

**Comment by hsandt** [comment]
Thanks, it also fixed Ctrl+drag folder not inserting link to directory!
