### ISSUE TITLE
[Feature Request]   The directory structure of the image is the same as the directory structure of the notes

### ISSUE THREAD

**Issue by muzhi1991** [RainCat1998/obsidian-custom-attachment-location#19]
if we have notes as tree:
- inbox
  - first.md
  - second.md
- journal
  - first.md
  - second.md

if set images root path in /assets, hope to have same directory structure 
- assets 
  - inbox
    - first
      - image-20220318xxx.png
      - image-20220318yyy.png
    - second
      - image-20220318xxx.png
      - image-20220318yyy.png
  - journal
    - first
      - image-20220318xxx.png
      - image-20220318yyy.png
    - second
      - image-20220318xxx.png
      - image-20220318yyy.png

now, if we set 'Location for New Attachments' = 'assets/${filename}', only have filename as directory

so, if implement this feature, we can have all image in one root  directory and easy to find all images of one note according path

thank you for this amazing plugin.

**Comment by RainCat1998** [comment]
Good suggestion. I will try to implement this feature in the next release.

**Comment by znning** [comment]
> Good suggestion. I will try to implement this feature in the next release.

When to release a new version?

**Comment by bananensplit** [comment]
Hey!
Are there any updates on this or a is there a timeline when this feature will be added?
Is there maybe a workaround that achives the above structure?
This featuer would make my life a lot easier :)

**Comment by dolandemort** [comment]
For any still interested in this feature, I discovered the plugin [Attachment Management](https://github.com/trganda/obsidian-attachment-management) to provide this option by default. It provides the variables `${notename}` and `${notepath}`.

**Comment by mnaoumov** [comment]
Implemented in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/3.3.0
