### ISSUE TITLE
I want to use the name of my parent folder as the attachment folder name. 

### ISSUE THREAD

**Issue by knightddd** [RainCat1998/obsidian-custom-attachment-location#24]
How to write the variable of the parent folder?Thanks！

**Comment by 23727** [comment]
I would like to know this as well

**Comment by sedghi** [comment]
This is very much the most general case https://github.com/RainCat1998/obsidian-custom-attachment-location/issues/19

**Comment by mnaoumov** [comment]
Implemented in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/3.3.0
