### ISSUE TITLE
Hidden folder

### ISSUE THREAD

**Issue by lapolis** [RainCat1998/obsidian-custom-attachment-location#31]
Hi there,

I was trying to use a hidden folder `./.screens/${filename}` as the `Location for New Attachments` but it does not work when I paste some images. All the other settings are still the default one.

The folder and subfolder are correctly created but the file (PNG picture in this case) never appear in the folder nor in the note.

Let me know if you need more info.

**Comment by RainCat1998** [comment]
Hidden folder can not recognize by obsidian, so you can't use hidden folder (filename staring with dot) for attachment folder.

**Comment by lapolis** [comment]
Oh no that's unfortunate :( I thought I finally found a way to hide the screenshoots while keeping them in the note's folder. 

Well, thanks for the clarification! :)
