### ISSUE TITLE
Plugin not supported on mobile

### ISSUE THREAD

**Issue by scottbilas** [RainCat1998/obsidian-custom-attachment-location#32]
When I try to add this plugin on my Android tablet, I see the below error "This plugin does not support your device". Is it not supported by design?

![image](https://user-images.githubusercontent.com/964720/183510461-54948a1c-d685-4c71-b647-38a250867522.png)

**Comment by RainCat1998** [comment]
Yes, currently, this plugin doesn't support mobile platforms.
