### ISSUE TITLE
Disappearing Attachments

### ISSUE THREAD

**Issue by hpatner** [RainCat1998/obsidian-custom-attachment-location#34]
I was playing around with the attachment location plugin and now certain attachment images seem to have disappeared. I get a box where the attachment was. Any suggestions?
![image](https://user-images.githubusercontent.com/5373835/195188299-64a9f2b3-1159-4acf-b717-a8ca57a7d8f5.png)

**Comment by RainCat1998** [comment]
Can you create a new vault with the attachment location plugin only to help reproduce the bug?
