### ISSUE TITLE
add pasted image name variable

### ISSUE THREAD

**Issue by sz9751210** [RainCat1998/obsidian-custom-attachment-location#36]
Hi could add variable without whitespace like this? Thanks

<img width="324" alt="image" src="https://user-images.githubusercontent.com/43094545/199390053-918ed932-9f60-44f0-8b6a-4c2def79f8cd.png">

default is blow

<img width="283" alt="image" src="https://user-images.githubusercontent.com/43094545/199390379-96fe1c29-7aef-47d9-84a1-1e011e459f3c.png">

**Comment by RainCat1998** [comment]
Yes, modify the format string in settings. (eg. test-${date})

**Comment by sz9751210** [comment]
could add format string like test-${num} ?

**Comment by RainCat1998** [comment]
> could add format string like test-${num} ?

I will consider this feature, but I haven't found a way to implement it. It's difficult to trace the pic number for every document.

**Comment by RainCat1998** [comment]
> could add format string like test-${num} ?

There are many conditions to keep the number updated when the file is deleted or renamed. But I will consider implementing it as an experimental feature.

**Comment by sz9751210** [comment]
ok thanks. the plugin is very helpful

**Comment by mnaoumov** [comment]
Implemented in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/3.2.0
