### ISSUE TITLE
Fully Control pasted link text (for default size)

### ISSUE THREAD

**Issue by ryanwwest** [RainCat1998/obsidian-custom-attachment-location#38]
When I paste an image, I usually want to resize the image to make it smaller, so I change `![[2022-12-07-1438.jpeg]]` to `![[2022-12-07-1438.jpeg|200]]`. I'd like to automatically add the `|200` upon paste so I don't always need to do it myself, and this could potentially be accomplished by allowing the user to fully customize what text is pasted (could also disable the default embedding of images by removing the preceeding `!`... I wouldn't do this but perhaps someone would).

**Comment by RainCat1998** [comment]
Your request is beyond the scope of this plugin. You can use regular expression to do it.
