### ISSUE TITLE
Obsidian Canvas ?

### ISSUE THREAD

**Issue by timvdhoorn** [RainCat1998/obsidian-custom-attachment-location#39]
Hello,

Will it be possible to use this with Obsidian Canvas? 

Thanks!

**Comment by Elaws** [comment]
Yes, would be really great. It's unfortunate that the plugin is not maintained anymore.

**Comment by RainCat1998** [comment]
> > > Yes, would be really great. It's unfortunate that the plugin is not maintained anymore.
> > 
> > 
> > I will reconstruct this plugin these days. There are so many updates of obsidian since last release.
> 
> Hello, do you have any news regarding the reconstucting? Thanks!

I was trying to reconstruct this plugin  a few weeks ago. 
Obsidian official API lacks of support for many hook operations. So the key point is finding other way to hook editor events BUT I didn't succeed yet.

**Comment by RainCat1998** [comment]
> > > Yes, would be really great. It's unfortunate that the plugin is not maintained anymore.
> > 
> > 
> > I will reconstruct this plugin these days. There are so many updates of obsidian since last release.
> 
> Hello, do you have any news regarding the reconstucting? Thanks!

I will release a new version today.

**Comment by Elaws** [comment]
Is this version supposed to support drag&drop and copy paste in Canvas ? Or only drag&drop ?

**Comment by hiforrest** [comment]
> > > > Yes, would be really great. It's unfortunate that the plugin is not maintained anymore.
> > > 
> > > 
> > > I will reconstruct this plugin these days. There are so many updates of obsidian since last release.
> > 
> > 
> > Hello, do you have any news regarding the reconstucting? Thanks!
> 
> I will release a new version to support this feature and add some new features. If you want to test this feature NOW, you can use my latesd dev build. [obsidian-custom-attachment-location_dev.zip](https://github.com/RainCat1998/obsidian-custom-attachment-location/files/11874134/obsidian-custom-attachment-location_dev.zip)

Thank you for creating this plugin, it's great and I have been using it. 
I just tried the dev version and it still cannot save pasted images to the corresponding folder. I am really looking forward to that you can overcoming the challenge and achieving perfect support for canvas. Keep up the good work!

**Comment by RainCat1998** [comment]
> > > > > Yes, would be really great. It's unfortunate that the plugin is not maintained anymore.
> > > > 
> > > > 
> > > > I will reconstruct this plugin these days. There are so many updates of obsidian since last release.
> > > 
> > > 
> > > Hello, do you have any news regarding the reconstucting? Thanks!
> > 
> > 
> > I will release a new version to support this feature and add some new features. If you want to test this feature NOW, you can use my latesd dev build. [obsidian-custom-attachment-location_dev.zip](https://github.com/RainCat1998/obsidian-custom-attachment-location/files/11874134/obsidian-custom-attachment-location_dev.zip)
> 
> Thank you for creating this plugin, it's great and I have been using it. I just tried the dev version and it still cannot save pasted images to the corresponding folder. I am really looking forward to that you can overcoming the challenge and achieving perfect support for canvas. Keep up the good work!

Sorry for the late reply. What I have updated in this build is changing "attachment folder" setting everytime canvas file is opened(only by "file-open" event).  But for markdown file, this can be done in the "editor-paste" OR "editor-drop" event. This is the only way to support canvas.

**Comment by RainCat1998** [comment]
> > > > > Yes, would be really great. It's unfortunate that the plugin is not maintained anymore.
> > > > 
> > > > 
> > > > I will reconstruct this plugin these days. There are so many updates of obsidian since last release.
> > > 
> > > 
> > > Hello, do you have any news regarding the reconstucting? Thanks!
> > 
> > 
> > I will release a new version to support this feature and add some new features. If you want to test this feature NOW, you can use my latesd dev build. [obsidian-custom-attachment-location_dev.zip](https://github.com/RainCat1998/obsidian-custom-attachment-location/files/11874134/obsidian-custom-attachment-location_dev.zip)
> 
> Thank you for creating this plugin, it's great and I have been using it. I just tried the dev version and it still cannot save pasted images to the corresponding folder. I am really looking forward to that you can overcoming the challenge and achieving perfect support for canvas. Keep up the good work!

Community plugins are restricted to use Obsidian API. If you can find someway to use other API, maybe this feature can be implemented.

**Comment by jiajiala** [comment]
移动canvas的时候，附件文件夹不会跟着移动

**Comment by Qxtron** [comment]
Hello,

[obsidian-custom-attachment-location-dev2.zip](https://github.com/RainCat1998/obsidian-custom-attachment-location/files/13793012/obsidian-custom-attachment-location-dev2.zip)



This is modify plugin 0.0.9 + dev. 
Supports:
- ".md" and ".canvas" note-files.
- autoRename attachments folder when rename a note.
- transfer note between folders.
- disabled autoRenameFiles in attachments folder when rename a note.
- disabled autoRename when paste image from buffer.

I have attachment folder near a note. 
<img width="351" alt="settings" src="https://github.com/RainCat1998/obsidian-custom-attachment-location/assets/155153913/67ecb089-a3e5-4ce2-ba63-e9fd7b96f9fd">

And hide attachment folder with plugin "Hide Folders" 
<img width="388" alt="hide folders" src="https://github.com/RainCat1998/obsidian-custom-attachment-location/assets/155153913/12b6daae-7041-448d-985a-bfd275ca5a26">


You can also refactor the code.

**Comment by mnaoumov** [comment]
Implemented in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/3.1.0

**Comment by Elaws** [comment]
Hi @mnaoumov : Sorry but not sure how to use "custom attachment location" with canvas ?

**Comment by mnaoumov** [comment]
@Elaws you just drag or copy-paste image from your `File Explorer / Finder` into your canvas in Obsidian and the image will go to the location according to the plugin settings

**Comment by Elaws** [comment]
> @Elaws you just drag or copy-paste image from your `File Explorer / Finder` into your canvas in Obsidian and the image will go to the location according to the plugin settings

Hi @mnaoumov , sorry I meant can we create a canvas file which will be automatically put in the appropriate folder (e.g. attachment folder in the folder of the current note) with appropriate name (e.g. note name with number increment) ?

**Comment by mnaoumov** [comment]
@Elaws no, because canvas files are naturally first-class citizens same as markdown files and bases files, so they are not treated as attachments.

While I don't recommend it, what you request is possible to do using three steps.

1. Configure `.canvas` as attachments in the plugin settings
2. Add canvas file to the markdown note
3. Invoke `Collect attachments in current note` command
