### ISSUE TITLE
Feature request:Attachment, instead of saved aside file,centralized save in one folder/Subfolders(named filename)

### ISSUE THREAD

**Issue by Masktial** [RainCat1998/obsidian-custom-attachment-location#4]

**Comment by Masktial** [comment]
**now:**
filefolder-
              -file
              -filename(folder)-
                                        -images
assetfolder-

**Hope get choices  setting as below:** 
filefolder-
              -file
assetfolder-
                 -filename(folder)-
                                           -images

love your works~!

**Comment by RainCat1998** [comment]
I will consider this feather and add to next release.

**Comment by RainCat1998** [comment]
@Masktial I have uploaded a new release. Have a try.
