### ISSUE TITLE
[feature request] Can we support ${prompt} when paste screenshoot

### ISSUE THREAD

**Issue by fushuang001** [RainCat1998/obsidian-custom-attachment-location#40]
it's a great extensition that could define the ${file} and ${date} with the image location & filename.
sometimes I want to make the filename more meaningful and the VsCode extension "Markdown Image" just support ${prompt}: Makes it possible to enter a custom name through an input prompt when pasting the image.

**Comment by mnaoumov** [comment]
Implemented in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/2.1.0
