### ISSUE TITLE
How to target the vault root folder?

### ISSUE THREAD

**Issue by Drakemoor** [RainCat1998/obsidian-custom-attachment-location#41]
Is there a way to target a specific folder in the root of the vault?
-Vault Root
--Attachments
--Notes
---note.md

Is there a way when I paste an image into note.md it automatically be saved into Attachments/note/ folder?
tnx

**Comment by TOGEP** [comment]
For the directory structure like this:
```
Vault Root
├── Attachments
└── Notes
    └── note.md
```

I think you can simply specify `Attachments/${filename}` for the "Location for New Attachments".
