### ISSUE TITLE
How to keep the original image filename?

### ISSUE THREAD

**Issue by Erimus-Koo** [RainCat1998/obsidian-custom-attachment-location#43]
I do like this plugin, it provides me with a Typora experience. But it still has some features that make me not adapt to it.

OS: Mac
- I've set the name of my image file. (I want to keep it)
- Copy the file from Finder.
- Paste it in Obsidian with this plugin.
- If the "pasted image name" has set some value, like `${date}`, the image file name would be changed.
- The paste will fail if the "pasted image name" is empty.

I want to keep the name of the image file as a local file name, or the name from the internet. Is it possible?

Add some options that may be solutions:
- Auto rename image on/off.
- Ignore the image file from the same folder(src&dst).
- After pasting the image, add a select with options of keep the src name or the suggested name.

I know typing `![[`, then selecting the image file from the files' list could work, but there are many images in my folder, and I'd like to choose images from Finder.

**Comment by vandermondeDET** [comment]
I couldn't agree more!
The latest version will **failed** if I paste **more than 1** picture **at a time**. As students, mostly we need to paste many pictures exported from a pdf or ppt. If it can support keeping the original filename(just like what obsidian itself does), things will be much better.
Thanks.

**Comment by mnaoumov** [comment]
Implemented in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/1.3.0
