### ISSUE TITLE
Toggle image renaming [feature request]

### ISSUE THREAD

**Issue by juffis** [RainCat1998/obsidian-custom-attachment-location#45]
I would like to have an option to toggle image renaming on / off. Currently I'm renaming files and giving images descriptive names, so I'd like to be able to disable this plugin from force renaming my images. I like the attachment location option with {filename} variable, really handy, but renaming images is unnecessary for me. Is there a way to disable it and if not, please make this a feature.

**Comment by RainCat1998** [comment]
In the current version, NO.  But I'm planning to reconstruct this project to support the latest obsidian.

**Comment by juffis** [comment]
I understand.
