### ISSUE TITLE
Images are pasted in duplicate

### ISSUE THREAD

**Issue by Jacobparresgold** [RainCat1998/obsidian-custom-attachment-location#48]
Thanks for the great plugin, this is just what I was looking for. However, I'm experiencing a bug where pasting an image pastes two copies: one via the obsidian-custom-attachment-location (in my desired folder), but another link and file in the default Obsidian behavior (the main attachments folder for my entire vault). This behavior remains after disabling all other community plugins and does not occur when images are dragged.

Here is a typical response I see after pasting an image:
![image](https://github.com/RainCat1998/obsidian-custom-attachment-location/assets/67981041/8a3793f7-e4f4-4b0c-a607-8e1a72067056)
(the first image is the desired one from obsidian-custom-attachment-location, the second is default Obsidian)

Below are screenshots of my settings for reference.
![image](https://github.com/RainCat1998/obsidian-custom-attachment-location/assets/67981041/15024636-4a1d-4ab7-b480-7f5097e646d5)
![image](https://github.com/RainCat1998/obsidian-custom-attachment-location/assets/67981041/91907af2-80b7-4469-9370-74c5b62c8cf9)

**Comment by RainCat1998** [comment]
Can you give the full test vault folder?

**Comment by Jacobparresgold** [comment]
I'll mark this as resolved
