### ISSUE TITLE
automatic renaming of attachment folder on filename change

### ISSUE THREAD

**Issue by daeh** [RainCat1998/obsidian-custom-attachment-location#5]
your plugin is working flawlessly. Thanks a ton for making this, it's really useful.

I imagine this would take a bit of work, but just wanted to suggest that it'd be a great feature if there was a way to keep the attachment folder name synchronized with the note's filename. I often rename notes and it'd be fantastic if there was a way to automatically rename the attachment folder and associated links.

**Comment by RainCat1998** [comment]
@daeh That's a great suggestion and I also have troubles when renaming md files. If it is possible, I will add it to the next release(Maybe this week).

**Comment by daeh** [comment]
in the off-chance it's useful, the https://github.com/dy-sh/obsidian-consistent-attachments-and-links plugin could be a useful reference

**Comment by RainCat1998** [comment]
@daeh I have uploaded a new release. Have a try.

**Comment by daeh** [comment]
It is working incredibly well, and it seems robust to a bunch of weird things I tried. I'm thrilled. This feature could be a stand-alone plugin and would be awesome even by itself. Thank you, this was the biggest convenience I was missing in obsidian.
