### ISSUE TITLE
[bug] Paste doesn't work if configured directory contains "." (dot)

### ISSUE THREAD

**Issue by SathOkh** [RainCat1998/obsidian-custom-attachment-location#50]
I'm trying to configure the name starting from "." (dot). It's standard for hidden files/directories on Linux.

Steps to reproduce:
1. Configure as follow
![image](https://github.com/RainCat1998/obsidian-custom-attachment-location/assets/2511493/6ddf314a-c5ec-40c3-8192-4960d2fc4b02)
2. E.g. make screenshot 
3. Try to paste

Expected result:
- Directory  created with file inside
- image pasted into note

Actual result:
- nothing happens

**Comment by mnaoumov** [comment]
dot-folders such as `.images` are not supported by the plugin because they are not tracked by Obsidian.

The settings will show an error if you try to use them starting from https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/1.0.1
