### ISSUE TITLE
The cursor automatically creates a blank line after you paste the picture

### ISSUE THREAD

**Issue by jiajiala** [RainCat1998/obsidian-custom-attachment-location#51]

**Comment by mnaoumov** [comment]
Works as intended for better formatting purposes

**Comment by luckman212** [comment]
Could this be made optional though? For me, the double blank line is always something I have to go back and clean up.

**Comment by luckman212** [comment]
@mnaoumov Seems like v3.0.0 no longer putting the blank lines, thank you for this 🙏 I much prefer this!
