### ISSUE TITLE
it seems there are no detection of the existence of the folder

### ISSUE THREAD

**Issue by librix** [RainCat1998/obsidian-custom-attachment-location#52]
I write `./${filename}.md/assets` in Location box. But when inserting a image to a note, the image file was never created successfully. 

I don't think the plugin has the ability to check if a directory exists and generate one if it doesn't. Is it possible to add this feature to the next release?

**Comment by mnaoumov** [comment]
@librix 

You cannot have `./${filename}.md` folder as it has the same name as the corresponding note. Consider removing `.md` suffix
