### ISSUE TITLE
attachment path add a available ${date} just like qq store attachment by month

### ISSUE THREAD

**Issue by minghepark** [RainCat1998/obsidian-custom-attachment-location#54]
Can you add a date variable to the attachment path? I want to create a new folder every month according to the date to store the attachment file of the corresponding month, just like qq stores the received pictures.

In addition, is there any conflict between this plug-in and local images plus? It needs to be combined with this plug-in to automatically download all web images and store them in the corresponding month folder according to the date.

**Comment by Harrd** [comment]
same problem

FYI
https://github.com/RainCat1998/obsidian-custom-attachment-location/pull/56

**Comment by mnaoumov** [comment]
Added in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/1.0.0
