### ISSUE TITLE
A sugestion: could we name files as ${filename}-${date}, or even  ${filename}-${counter}

### ISSUE THREAD

**Issue by ndharari** [RainCat1998/obsidian-custom-attachment-location#6]
just in the title

**Comment by RainCat1998** [comment]
@ndharari The latest release supports ${filename} in image name. Have a try.

**Comment by ndharari** [comment]
its not working for me. i'm using as setting ${filename}-${date} and It does not let me paste any image

**Comment by ndharari** [comment]
working perfectly!
