### ISSUE TITLE
Issue: Custom Attachment Directory Not Created Correctly for Non-Image Attachments (e.g., PDF)

### ISSUE THREAD

**Issue by Harrd** [RainCat1998/obsidian-custom-attachment-location#60]
# Description
When copying or dragging non-image attachments (such as PDFs), I found that the custom attachment directory is not created correctly, and the attachments are placed in the root directory.

# Causes
- In the drop event: The folder is created using an asynchronous API, but Obsidian's native drop event might execute first, causing the operation to fail.
- In the paste event: Only the paste of image-type resources is overridden, and there is no specific handling for PDFs. This also encounters the same issue as in point 1.

# Possible Solution
For the drop event, a potential solution I thought of is to first prevent the default drop event, wait for the directory to be created and then re-dispatch the native Obsidian drop event.

However, I am not familiar with the Obsidian API and do not know how to re-dispatch the original event. Can someone provide some information or help fix this?

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/2.0.0
