### ISSUE TITLE
Error While Pasting Text

### ISSUE THREAD

**Issue by ProudBenzene** [RainCat1998/obsidian-custom-attachment-location#62]
Current plugin version: 3.0

After pasting normal text, it will automatically be pasted one more time, unless the plugin is disabled.

**Comment by mnaoumov** [comment]
@ProudBenzene can you please record a video? I can't reproduce it. What operating system do you have?

**Comment by ProudBenzene** [comment]
Thanks for replying so quickly!

I'm on macOS, and Just now as I was getting ready to record the video, I also realized that not all copy and pastes reproduce the problem. Only copying in **list** format will reproduce it. Could you please try again?

**Comment by mnaoumov** [comment]
@ProudBenzene I don't understand what is **list** format. I need an example

**Comment by ProudBenzene** [comment]
Okay, here is the record video: 


https://github.com/user-attachments/assets/7cc9e2e6-027c-4eb0-b876-eb96e4bee842

**Comment by mnaoumov** [comment]
@ProudBenzene I still cannot reproduce the issue. Can you please to disable all other plugins and keep only the current one to see if the issue stays

**Comment by ProudBenzene** [comment]
Seems like the problem was solved after I updated the latest version of the plugin.

Thank you very much!
