### ISSUE TITLE
Drag&Drop Behavior changed

### ISSUE THREAD

**Issue by jesusmnv** [RainCat1998/obsidian-custom-attachment-location#63]
Hi bro, on activate this plugin the behavior for drag&drop over other files changed and instead paste WikiLink, shows an HTML, could you please update for maintain WikiLink?

https://github.com/user-attachments/assets/b2416cef-438d-4d8a-9d25-c8bad9f9eba9

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/3.5.0
