### ISSUE TITLE
[feature request]  add .gitkeep as an optional choice

### ISSUE THREAD

**Issue by Harrd** [RainCat1998/obsidian-custom-attachment-location#64]
https://github.com/RainCat1998/obsidian-custom-attachment-location/commit/dbd3ce4e9b335782db716ad2bac453813314ba3c#commitcomment-144805701

**Comment by mnaoumov** [comment]
Added in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/3.6.0
