### ISSUE TITLE
Request for relative link

### ISSUE THREAD

**Issue by jiaanliux** [RainCat1998/obsidian-custom-attachment-location#65]
Currently, this plug-in will modify all pasted links into a full path. 

For example, `![[/User/MacUser/Notes/Project1/assets/111.jpg)]]`.

But when moving the place of the project folder (the vault), this link will not work any more.

So, the best way may be using a **relative path**: `![./assets/111.jpg)]]`

**Comment by mnaoumov** [comment]
@jiaanliux 

It seems you are using `Absolute path in vault` setting

![image](https://github.com/user-attachments/assets/14a1f049-b278-46c1-be34-64556de42839)

The plugin doesn't generate the links on its own. It relies on built-in Obsidian function which respects corresponding Obsidian settings
