### ISSUE TITLE
Text paste not working in Live Preview and Source mode with in-page Find box

### ISSUE THREAD

**Issue by pdanford** [RainCat1998/obsidian-custom-attachment-location#67]
- macOS 14.6
- Obsidian 1.6.7
- Custom Attachment Location 3.7.0

### To reproduce:

1. open a page in Live Preview or Source mode
2. with no text selected, <kbd>command</kbd><kbd>f</kbd> to open an in-page Find box
3. select and copy a word from text using <kbd>command</kbd><kbd>c</kbd> or the right click menu
4. now try to paste in the previously opened page Find box with both <kbd>command</kbd><kbd>v</kbd> or the right click menu
5. nothing appears in Find box

Note: The only way to get text into the Find box is to have it selected before you open the box with <kbd>command</kbd><kbd>f</kbd>

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/3.8.0
