### ISSUE TITLE
If note is renamed, all attachment links convert to `![[attach/foo/bar|bar]]`

### ISSUE THREAD

**Issue by luckman212** [RainCat1998/obsidian-custom-attachment-location#68]
I noticed since updating to 4.0.0 that when renaming a note, all attachment links are converted from e.g.

```md
![[IMG-20240802120853157.png]]
```

to

```md
![[attach/My Super Long Note Title with a lot of words in it/IMG-20240802120853157.png|IMG-20240802120853157.png]]
```

This is not ideal (at least for me). It adds a lot of extra verbosity to the notes and also causes all images to get a subtitle (because I have the [image captions](https://github.com/alangrainger/obsidian-image-captions) plugin installed).

Is there any way to revert this behavior or at least make it optional?

**Comment by mnaoumov** [comment]
@luckman212 please check

![image](https://github.com/user-attachments/assets/a1495908-3660-4dca-957c-68e82ec6a2c7)

It seems that you have `Absolute path in vault` setting set.

That's what the plugin is based on when it generates updated links

**Comment by luckman212** [comment]
Thanks @RainCat1998 but, negative... Here are my settings:

<img width="1100" alt="image" src="https://github.com/user-attachments/assets/1a1616d1-7dec-48ac-aedd-9cea06b3d737">

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.1.0

**Comment by luckman212** [comment]
@mnaoumov I really appreciate this quick fix!
