### ISSUE TITLE
How do I ignore dragged-in files that are not images?

### ISSUE THREAD

**Issue by luckman212** [RainCat1998/obsidian-custom-attachment-location#69]
I dragged a JSON file into my vault just now and it renamed it to `IMG-XXXXX.json`

How can I tell the plugin to ignore any attachment that isn't a JPEG or PNG? 🙏 

Here are my settings currently:

<img width="644" alt="image" src="https://github.com/user-attachments/assets/82ff7708-f6cd-473a-9224-bb6fac37a99b">

**Comment by mnaoumov** [comment]
Implemented in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.2.1
