### ISSUE TITLE
The problem of custom folder

### ISSUE THREAD

**Issue by hidegger** [RainCat1998/obsidian-custom-attachment-location#7]
Hi! Thanks for your plugin. Some remarks:
1. The plugin resets the custom folder to "assets". If I try to change the folder to something like "Images/${filename}" it will anyway reset and save to "assets".
2. Is there any way to use the top-level folders? For example "../Images/${filename}"?

Obsidian 0.13.19.

**Comment by RainCat1998** [comment]
@hidegger  I have uploaded a new release. Have a try.

**Comment by hidegger** [comment]
Works perfectly! You're the best, man! Thanks!
