### ISSUE TITLE
When pasting text, will paste twice

### ISSUE THREAD

**Issue by flmn** [RainCat1998/obsidian-custom-attachment-location#70]
If custom-attachment-location is enabled, when paste on new note title, will paste twice.

https://github.com/user-attachments/assets/b4fe699e-9e8e-4e64-89e2-90a26a423242

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.3.2
