### ISSUE TITLE
Error when you change the name of the file and you have images in the file

### ISSUE THREAD

**Issue by dbloper** [RainCat1998/obsidian-custom-attachment-location#72]
When I rename the file and I have an image inside the file, it shows an error and does not change the name of the image, and it does not change the name of the folder either and instead of renaming the name of the folder, it creates a new folder with the new name of the file
I share my configuration and the error

<img width="508" alt="image" src="https://github.com/user-attachments/assets/11fadaf9-0f25-4984-89f5-1e68afbb22ab">

<img width="654" alt="image" src="https://github.com/user-attachments/assets/f0b98e2f-58c9-4bea-be6a-fb3e80e86154">

**Comment by mnaoumov** [comment]
@dbloper Cannot reproduce the issue. Please provide a sample vault and a video with the issue

**Comment by dbloper** [comment]
Hi, I just updated to version 4.6.0 and this issue has been fixed.

This is a great plugin

Thank you very much
