### ISSUE TITLE
Move attachment folder 

### ISSUE THREAD

**Issue by dbloper** [RainCat1998/obsidian-custom-attachment-location#74]
In previous versions when you moved the file note the attachment folder was also moved...not now, this feature was very practical

**Comment by mnaoumov** [comment]
@dbloper Cannot reproduce the issue. Please provide a sample vault and a video with the issue

**Comment by dbloper** [comment]
Hi, I just updated to version 4.6.0 and the problem is solved.

Thank you very much, this is an excellent plugin
