### ISSUE TITLE
Relation to dy-sh/obsidian-consistent-attachments-and-links ?

### ISSUE THREAD

**Issue by luckman212** [RainCat1998/obsidian-custom-attachment-location#76]
I see @mnaoumov is the author of most of the commits to both this as well as the similar https://github.com/dy-sh/obsidian-consistent-attachments-and-links plugin. 

Are these plugins serving different purposes? Any reason to choose one vs. the other?

**Comment by mnaoumov** [comment]
@luckman212, yes, the plugins are different

- [`Obsidian Custom Attachment location`](https://github.com/RainCat1998/obsidian-custom-attachment-location/) allows to have custom attachment folder based on file name, date, etc
- [`Consistent Attachments and Links`](https://github.com/dy-sh/obsidian-consistent-attachments-and-links) ensures that all links are valid and allows to collect corresponding attachments to their notes.

I personally use them together, but technically they don't depend on each other.

**Comment by luckman212** [comment]
Okay thanks @mnaoumov - I personally only see the need for Obsidian Custom Attachment Location at the moment but it's good to know the 2 can coexist, I thought they would interfere with each other...
