### ISSUE TITLE
FR: "Collect attachments..." commands: add warning, also perform file renames for consistency

### ISSUE THREAD

**Issue by luckman212** [RainCat1998/obsidian-custom-attachment-location#77]
_This is a continuation of the discussion from #75_

This relates to the 3 custom commands that are added by this plugin:

- Collect attachments in current note
- Collect attachments in entire vault
- Collect attachments in current folder

### FR: Add confirmation / warning

I'm afraid to try the 2 commands highlighted below, because I fear they will just run without any confirmation and could be destructive, and there is no "undo" for this. I propose that for any command which operates on multiple notes—especially the _entire vault_—there should be a confirmation dialog giving the user an opportunity to cancel.

<img width=500 src=https://github.com/user-attachments/assets/fdab9f54-7b0c-4f74-9976-223256cf3609>

### FR: Rename attachments when executing the _"Collect attachments in..."_ commands

I suggest that for consistency, when running e.g. _"Collect attachments in current note"_ that linked images e.g. `Pasted image 20221102112355.png` should be normalized using the same rules that would be applied if I had copied and pasted that image into the note. If that is not ideal for everyone, then a toggle to control this would be great of course!

> I thought initially that the sister plugin [Consistent Attachments and Links](https://github.com/dy-sh/obsidian-consistent-attachments-and-links) would have this function, but after testing it seems I was wrong. So I propose to add it here.

**Comment by luckman212** [comment]
For now, I've used the [Command Block List](https://github.com/RyotaUshio/obsidian-command-block-list) plugin to hide those bottom 2 commands to prevent myself from accidentally triggering them.

@mnaoumov Is this FR something you would consider? I can try to work on it and submit a PR if you want.

**Comment by mnaoumov** [comment]
Yes, I would consider. Although, they are two independent FRs

**Comment by luckman212** [comment]
I agree. Ok I wait for bugfix in #83 and then see if I can create these 2 FRs.

**Comment by mnaoumov** [comment]
Warning added in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.11.0

**Comment by mnaoumov** [comment]
Renaming attachments added in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.12.0

**Comment by luckman212** [comment]
Thank you so much for this. This plugin is superb and just keeps getting better!
