### ISSUE TITLE
Attachment folder got delete when delete note

### ISSUE THREAD

**Issue by iinicolelam** [RainCat1998/obsidian-custom-attachment-location#78]
I put all my attachments within the same Attachments folder and when I delete one note (even if there is no attachment). Below are my settings.

![image](https://github.com/user-attachments/assets/10ee0f83-b5a6-4264-ac6d-8f6e61c6808e)

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.9.1
