### ISSUE TITLE
Drag and drop does not use custom attachment name

### ISSUE THREAD

**Issue by Elaws** [RainCat1998/obsidian-custom-attachment-location#8]
Hello,

Thanks for this great plugin ! I just noticed that drag and drop still does not work : it does not change the image name to my custom name (${filename}).

Wasn't the latest release supposed to solve that issue ?

Thanks !

Obsidian 0.13.19
Plugin 0.0.6
Windows 10 21H2

**Comment by RainCat1998** [comment]
No, it only affects filename of images from your clipboard. When handling drag & drop events, the plugin changes attachment folder setting before obsidian moving file and obsidian keeps the origin filename.

**Comment by RainCat1998** [comment]
It is hard to check the file type and rename target filename in drag & drop handler. I will consider how to implement this feather in an elegant way.

**Comment by Elaws** [comment]
Thanks for your reply ;)

My mistake, I misinterpreted on of the releases which had "drop support" as changelog

**Comment by RainCat1998** [comment]
> Thanks for your reply ;)
> 
> My mistake, I misinterpreted one of the releases which had "drop support" as changelog

I will consider this feather in the next release.

**Comment by Elaws** [comment]
This is a great news, thanks for your work ;)

**Comment by zeltak** [comment]
awesome plugin! would also love drag and drop as its my main way of putting images into obsidian

thx so much for your epic work!!

Z

**Comment by RainCat1998** [comment]
> I also noticed that copy/pasting from file explorer does not rename the file appropriately. It would be nice if there was an option to rename pasted files.

I have considered this before, but it is hard to do because obsidian only exposes a few APIs for plugin developer. You can use Chrome debugging console to view obsidian app.js source code, and I didn't find a perfect way to do this. Unless I hook and rewrite all original  copy&paste code.

**Comment by Elaws** [comment]
Hello, 

Is this bug fixed ? I just drag'n dropped a "jpeg" file from explorer to Obsidian and it is not renamed as expected.

Thank you
