### ISSUE TITLE
why the path not contained in the image block

### ISSUE THREAD

**Issue by cnzf1** [RainCat1998/obsidian-custom-attachment-location#80]
I write ./assets/${filename}.assets in Location box. But when inserting a image to a note, the tag ![](test.png) had not contained the directory. 

for example:  When insert a image in a file named file.md, I wish create a image in ./assets/file.assets/file-202408211532.png, and insert a code `![](./assets/file.assets/file-202408211532.png)`,  but I got `![](file-202408211532.png)`.

**Comment by mnaoumov** [comment]
It seems you have the following Obsidian settings.

![image](https://github.com/user-attachments/assets/47d82700-e6a4-4fc3-93fa-806391a45738)

The plugin doesn't construct links by itself, it relies on Obsidian's functions that rely on those settings
