### ISSUE TITLE
When rename folder name, an error ... 

### ISSUE THREAD

**Issue by xwshan** [RainCat1998/obsidian-custom-attachment-location#81]
- obsidian：1.6.7
- custom-attachment-location version：4.7.0
---
When renaming any folder, an error will be reported.
![image](https://github.com/user-attachments/assets/6e165b0e-213c-45fc-b7b5-9c706213fe3c)
like this.

---
- These settings:
![image](https://github.com/user-attachments/assets/376cd02a-6334-4250-8931-ecb1e0b5b498)

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.9.0
