### ISSUE TITLE
What happened to the setting panel?

### ISSUE THREAD

**Issue by luckman212** [RainCat1998/obsidian-custom-attachment-location#82]
In v4.9.1, the settings panel seems to be missing most of the options now...

<img width="1104" alt="image" src="https://github.com/user-attachments/assets/b66d1b25-ff7c-46a3-9782-2c0bcb761aa0">

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.9.2
