### ISSUE TITLE
Settings can't be saved

### ISSUE THREAD

**Issue by Novice-level** [RainCat1998/obsidian-custom-attachment-location#84]
After the plugin is set up, exit and re-enter, most of the settings are reset, except for "Pasted File Name" and "Location for New Attachments"

**Comment by lone17** [comment]
Same issue. Not sure if this is from obsidian or this tool. But I found out that it would save the very last setting that you change, so to go around this for now, you can change the setting one by one.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.10.0

**Comment by Novice-level** [comment]
> Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.10.0

Well, the problem has been solved. Thanks to the author.
