### ISSUE TITLE
Feature: allow hidden folders

### ISSUE THREAD

**Issue by Squirreljetpack** [RainCat1998/obsidian-custom-attachment-location#85]
When setting Location for Attachments, hidden folder names has become forbidden.
For compatibility reasons, could you remove or give us an option to override this restriction?
Since obsidian can be made to track hidden folders if using plugins like Show Hidden Files. And there are ways to have Obsidian track the files without displaying them.
Hidden folders are nice as they reduce visual clutter, and I believe Typora (used to?) have an attachment folder format of `./.${filename}.assets` -- I use this plugin to keep this format.
Thank you for your plugin.

**Comment by mnaoumov** [comment]
Implemented in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.10.0
