### ISSUE TITLE
Settings dialog always shows 0.1 for jpegQuality regardless of actual setting

### ISSUE THREAD

**Issue by luckman212** [RainCat1998/obsidian-custom-attachment-location#88]
I think this bug may actually lie in the imported obsidian-dev-utils module...

Each time settings dialog is closed and re-opened, the setting displays as **0.1**

![screenshot_9ULkZYzZ](https://github.com/user-attachments/assets/9abc1667-8ebd-4d99-8fb3-c631e5e31aab)

my data.json...

```js
{
  ...
  "duplicateNameSeparator": "-",
  "jpegQuality": 0.8,                   <==
  "keepEmptyAttachmentFolders": false
  ...
}
```

**Comment by luckman212** [comment]
related? https://github.com/mnaoumov/obsidian-dev-utils/issues/1

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.12.2

**Comment by luckman212** [comment]
Ah, thank you @mnaoumov - TIL. Thank you for fixing the actual bug in https://github.com/RainCat1998/obsidian-custom-attachment-location/issues/88
