### ISSUE TITLE
Request to customize the markdown link format of the file

### ISSUE THREAD

**Issue by at2008** [RainCat1998/obsidian-custom-attachment-location#89]
This plugin is very useful for me, thanks to the author! I have a new requirement, I wonder if it can be realized?

When wikilink is disabled in obsidian, paste an image into a markdown file whose file name contains whitespace, and the generated link will be like this:

`![](assets/my%20file/file-202409.png)`

I hope to add a configuration to generate a link format like this:

`![](<assets/my file/file-202409.png>)`

If the path name or file name contains spaces, use the `(<link>)` format link.

**Comment by mnaoumov** [comment]
This can be done via https://github.com/mnaoumov/obsidian-better-markdown-links

**Comment by at2008** [comment]
@mnaoumov 

Thanks for your reply, this plugin has the function I want, thank you!
