### ISSUE TITLE
Move attachments folder when the note file is moved

### ISSUE THREAD

**Issue by mnaoumov** [RainCat1998/obsidian-custom-attachment-location#9]
Currently if I move the note to another folder, I have to move attachments folder manually.

I was considering plugin https://github.com/dy-sh/obsidian-consistent-attachments-and-links it is extremely inefficient for big vaults

**Comment by mnaoumov** [comment]
It was actually not too hard to implement. I prepared a pull request for that

**Comment by RainCat1998** [comment]
I have considered your solution, but I'm not sure if 'file-open' handler is called before you switch your notes. If not, it may causes unexpected problems.

**Comment by mnaoumov** [comment]
@RainCat1998 It seems to be working fine as per my testing

**Comment by pitibalrog** [comment]
Hi
Is there a plan to include this solution to the next release ?

**Comment by mnaoumov** [comment]
@pitibalrog temporarily until the author releases a new version you can use my forked version.

The easiest way is to install [BRAT](https://github.com/TfTHacker/obsidian42-brat) plugin first and from it use **Add a beta plugin for testing** using the following url https://github.com/mnaoumov/obsidian-custom-attachment-location
