### ISSUE TITLE
Link conversion when file is renamed

### ISSUE THREAD

**Issue by at2008** [RainCat1998/obsidian-custom-attachment-location#91]
Disable wikilinks. When renaming files, the plugin will automatically convert `[text](<link>)` to `[text](link)`. If there are whitespaces in the link, they will be converted to `%20`. It is hoped that the link format of `[text](<link>)` can be maintained.

**Comment by mnaoumov** [comment]
Do you use https://github.com/mnaoumov/obsidian-better-markdown-links ? Is it the latest version?

**Comment by at2008** [comment]
> Do you use https://github.com/mnaoumov/obsidian-better-markdown-links ? Is it the latest version?

I have disabled this plugin [Better Markdown Links](https://github.com/mnaoumov/obsidian-better-markdown-links). I found that this plugin may automatically convert all `[text](link)` to `[text](<link)`. I haven't done too many careful tests. At present, I feel that it may be risky to the document. I will test it carefully later and give feedback.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.16.0
