### ISSUE TITLE
Deleting a note deletes all attachments without warning

### ISSUE THREAD

**Issue by luckman212** [RainCat1998/obsidian-custom-attachment-location#92]
I got caught off guard by this.

It's really an issue with https://github.com/mnaoumov/obsidian-dev-utils because the `RenameDeleteHandler.ts` is contained there. But I am reporting here since this is the user facing side.

I was doing some cleanup on my vault today, archiving some old notes. I have a folder called "Archive" which is OUTSIDE of my Main vault. I was dragging .md notes from the Finder into the Archive folder.

When I looked back after a few minutes, I saw that the plugin had happily deleted all of the attachment folders for these notes, which I was planning to also archive of course. They were not in the Obsidian trash, nor the system Trash, they were just gone.

Luckily I have hourly backups of my vault so I can recover from this without too much trouble, but I think this is a dangerous default. Even an accidental file move could cause irrevokable data loss.

I suggest 2 changes:

1. Make a setting toggle: ***Delete orphan attachment folders*** (default should be `false`)
2. Add a popup menu to select Deletion method:
   - Hard delete (`app.vault.delete(tfile)`)
   - System Trash (`app.vault.trash(tfile, true)`)
   - Obsidian Trash (`app.vault.trash(tfile, false)`)

see https://github.com/Canna71/obsidian-janitor/blob/5ca9cf13bb8b96814a2f24b323f96d52a2c805ec/src/FileProcessor.ts#L23-L35 for examples of the safer methods...

Thank you

**Comment by mnaoumov** [comment]
1. Done in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.18.0
2. The setting already exists in Obsidian itself. Now the plugin respects it

![image](https://github.com/user-attachments/assets/21dd9fa7-ff53-4d4e-a045-a541f1afe223)

**Comment by mnaoumov** [comment]
@luckman212 https://buymeacoffee.com/mnaoumov
