### ISSUE TITLE
When removing the last remaining note in a folder, it will delete all parent folders

### ISSUE THREAD

**Issue by JeffKoons** [RainCat1998/obsidian-custom-attachment-location#93]
This is probably not as much of a bug and more of an enhancement request. I have an "Inbox" folder where all initial notes go.  Under that Inbox, I have an '_attachments' folder and then I have this plug-in create a subfolder under _attachments, as the note filename (Inbox>_attachments>Note Title folder). As I'm processing my notes out of the inbox, when I move the last note out, it ends up deleting this whole Inbox folder structure. 

I also do have the 'Keep empty attachment folders' turned off, and my 'Location for New Attachments' is set to: ./_attachments/${filename}

I do like the fact that the plugin will cleanup the folder it created based on the filename, when I move the note, but I would like if it would stop there and not delete the inbox or the _attachments parent folders. Basically, it should just delete the lowest folder level set in Location for New Attachments. Or at the very least, it would be nice if could ignore any folder (like Inbox) where I have it set as the 'Folder to create new notes in' under Files and Links.

**Comment by mnaoumov** [comment]
I think, instead of adding this specific request to the plugin, you use a standard workaround such as [.gitkeep](https://gist.github.com/jlollis/54d3b3a7ed12776ac9f0d4bc13e63ed9)

**Comment by mnaoumov** [comment]
As you said `.gitkeep` is ignored and the folder is still removed, it's indeed a bug

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.19.0
