### ISSUE TITLE
Automatically rename attachment files ${filename} when renaming .md file is not working

### ISSUE THREAD

**Issue by keichhorn** [RainCat1998/obsidian-custom-attachment-location#94]
I use the following pasted Filename: file-${foldername}-${filename}-${date:YYYYMMDD}-${originalCopiedFilename}
The Option "Automatically rename attachment folder" and "Automatically rename attachment files" are both activated.

When renaming the .md file, die Attachment folder gets renamed, but not the filename in the attachment file.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.20.0
