### ISSUE TITLE
plugin:obsidian-custom-attachment-location:841 Error: Destination file already 

### ISSUE THREAD

**Issue by znning** [RainCat1998/obsidian-custom-attachment-location#95]
when run collect attachments in curren note,  error occured.I've uploaded my test notes。
![image](https://github.com/user-attachments/assets/766768c2-e36c-4ad6-9fb9-d81adc270783)
![image](https://github.com/user-attachments/assets/69600000-1b1e-4970-9f63-fa8a456f804b)

windows 11
obsidian v1.6.7

[test note.zip](https://github.com/user-attachments/files/16987519/test.note.zip)

**Comment by mnaoumov** [comment]
Please retest with https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.20.0

If the issue persists, please provide a copy of entire vault, not just note. And also record a video with the issue

**Comment by znning** [comment]
Add  entire vault and video gif
[obsidian_test.zip](https://github.com/user-attachments/files/17001343/obsidian_test.zip)
![动画](https://github.com/user-attachments/assets/cb21896c-8b9c-4db0-9c7a-8a4951f15441)

**Comment by znning** [comment]
![动画2](https://github.com/user-attachments/assets/87def635-d8af-41eb-8d12-ab3973e5c77d)

**Comment by znning** [comment]
[动画2.zip](https://github.com/user-attachments/files/17001351/2.zip)
