### ISSUE TITLE
Android 12 files not imported   

### ISSUE THREAD

**Issue by rxsend19** [RainCat1998/obsidian-custom-attachment-location#97]
![image](https://github.com/user-attachments/assets/53084cea-0e74-4062-80f9-854e1df947d7)
![image](https://github.com/user-attachments/assets/e25070b0-7a66-4e1c-a54d-c66220a1cd6d)
Uncaught (in promise) TypeError: app.vault.adapter.getBasePath is not a function  
plugin:obsidian-custom-attachment-location:7979

I got the error only when specifying an absolute path

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.22.0
