### ISSUE TITLE
when collecting a folder, console error hangs processing at a note. image removed and replaced with duplicated existing image

### ISSUE THREAD

**Issue by realizetm** [RainCat1998/obsidian-custom-attachment-location#98]
using current Obsidian (1.67) and Custom attachment location (4.20.0

app.js:1 Uncaught (in promise) Error: Destination file already exists!
    at e.<anonymous> (app.js:1:539722)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)
    
I watched it a few times. It would get stuck on a few notes, but am unable to ascertain what makes them special. I would confirm the images were correct, make any corrections, and move the note to a new file and begin again.

I made one last pass after bringing all notes back to the original folder, and reprocessed, and received this error and it got stuck on a note (Rice Paper recipe per image) that was fine. In evaluating the note, there was a duplicate image link. There were originally two images, side by side. Now still had two images, but the second image was no longer linked to the note.

There remain a large number (82/153) images that have not been processed and remain with "Pasted image 2024-mm-dd-2024mmddhhsss.png titles.

![image](https://github.com/user-attachments/assets/55b09fe1-e486-47e9-846c-0e294fb8c026)

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.21.0

**Comment by realizetm** [comment]
i will report if any issues. thanks so much!On 15 Sep 2024, at 6:32 p.m., Michael Naumov ***@***.***> wrote:﻿
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.21.0

**Comment by realizetm** [comment]
It doesn't seem to have corrected my issue. 

![image](https://github.com/user-attachments/assets/44f68e70-cfa1-449e-b064-9c1ce2781a3e)
![SCR-20240916-neni](https://github.com/user-attachments/assets/0dc5d380-0432-45c9-a5fe-2b934f32c78a)
![SCR-20240916-neec](https://github.com/user-attachments/assets/f020148e-71e8-4dd6-8889-bb4928a9b8e0)
![image](https://github.com/user-attachments/assets/57f8c7fe-4a1a-4509-8783-59aebbf61eb8)
![image](https://github.com/user-attachments/assets/d653584f-d3fd-4017-8324-bd699fcaccb5)

the dark mode is the in vault that was processed. the light mode is the original file that was copied into my vault from antoher vault. so it is the "before" you can see two separate images - - Old:
			- ![[Pasted image 20240104161539.png]]
		- New
			- ![[Pasted image 20240104161623.png]]
			
			
and in the processed vault - you can see the newly renamed images as:- Old:
			- ![[Change-Ledger-20240916140710136.png]]
		- New
			- ![[Change-Ledger-20240916140710136.png]]
			
			
Pasted image 20240104161623.png is no longer in the vault, nor in the Obsidian trash. Pasted image 20240104161539.png is now located in the Obsidian trash.

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.22.0
